behaviors:
  Triple:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 10240
      learning_rate: 1.0e-5
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.5
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 3000000
    time_horizon: 64
    summary_freq: 10000
    threaded: true
